apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: battlelog
resources:
  - ../../base
patches:
  - path: patch-app-deploy-image.yaml
  - path: patch-app-svc-nodeport.yaml
  - path: patch-config-preseed.yaml
