apiVersion: v1
kind: Service
metadata:
  name: battlelog-postgres
  labels:
    component: postgres
spec:
  type: ClusterIP
  selector:
    app: battlelog
    component: postgres
  ports:
    - name: pg
      port: 5432
      targetPort: 5432
