apiVersion: v1
kind: Service
metadata:
  name: battlelog-app
  labels:
    component: app
spec:
  type: ClusterIP
  selector:
    app: battlelog
    component: app
  ports:
    - name: http
      port: 3000
      targetPort: 3000
