apiVersion: v1
kind: Secret
metadata:
  name: battlelog-secrets
  labels:
    component: secrets
type: Opaque
stringData:
  POSTGRES_PASSWORD: "change_me"
  DATABASE_URL: "postgres://livelogiuser:change_me@battlelog-postgres:5432/livelogi"
